/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuingresso.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import meuingresso.Cliente;
import meuingresso.Funcionario;
import meuingressoDAO.ClienteDAOPG;
import meuingressoDAO.FuncionarioDAOPG;
import meuingressoDAO.PessoaDAOPG;

/**
 *
 * @author priscillabittencourt
 */
public class JFCadastrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFCadastrarCliente
     */
    public JFCadastrarCliente() {
        initComponents();
        jButtonCadastrar.setVisible(false);
        jButtonEditar.setVisible(false);
        jButtonExcluir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTDataNasc = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        JTCPF = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelNotificacao = new javax.swing.JLabel();

        jLabel8.setText("CPF");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro Cliente");

        jLabel2.setText("Nome Completo");

        JTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("E-mail");

        jLabel4.setText("CPF");

        jLabel6.setText("Telefone");

        jLabel7.setText("Data Nascimento");

        JTDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTDataNascActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        JTCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCPFActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNotificacao)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JTNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JTEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(JTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(JTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCadastrar)
                            .addComponent(JTDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabelNotificacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNomeActionPerformed

    private void JTCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCPFActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         ClienteDAOPG clienteDAO = new ClienteDAOPG();
        try {
            if(clienteDAO.retrieveOneByCPF(JTCPF.getText()) == null){
                JTDataNasc.setText("");
                JTEmail.setText("");
                JTNome.setText("");
                JTTelefone.setText("");
                JTCPF.setText("");
                
                jLabelNotificacao.setText("! - Cliente não localizado.");
                jButtonEditar.setVisible(false);
                jButtonExcluir.setVisible(false);
                jButtonCadastrar.setVisible(true);
                
            }else{
                Cliente cliente = clienteDAO.retrieveOneByCPF(JTCPF.getText());
                JTCPF.setText(cliente.getCpf());
                JTDataNasc.setText(cliente.getDataNascimento());
                JTEmail.setText(cliente.getEmail());
                JTNome.setText(cliente.getNome());
                JTTelefone.setText(cliente.getTelefone());
                jLabelNotificacao.setText("OK - Cliente localizado.");
                jButtonEditar.setVisible(true);
                jButtonExcluir.setVisible(true);
                jButtonCadastrar.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFCadastroSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        PessoaDAOPG pessoaDAO = new PessoaDAOPG();
        ClienteDAOPG clienteDAO = new ClienteDAOPG();
        try {
            Cliente cliente = new Cliente(JTNome.getText()
                    , JTCPF.getText()
                    , JTEmail.getText()
                    , JTTelefone.getText()
                    , JTDataNasc.getText());
            System.out.println(cliente);
            pessoaDAO.create(cliente);
            int id = pessoaDAO.retrieveIdPessoaByCPF(JTCPF.getText());
            cliente.setId(id);
            clienteDAO.create(cliente);
            jLabelNotificacao.setText("OK - Cliente cadastrado com sucesso!");
            JTDataNasc.setText("");
            JTEmail.setText("");
            JTNome.setText("");
            JTTelefone.setText("");
            JTCPF.setText("");
            jButtonEditar.setVisible(false);
            jButtonExcluir.setVisible(false);
            jButtonCadastrar.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(JFCadastroSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
       ClienteDAOPG clienteDAO = new ClienteDAOPG();
       PessoaDAOPG pessoaDAO = new PessoaDAOPG();
        try {
            Cliente cliente = clienteDAO.retrieveOneByCPF(JTCPF.getText());
            cliente.setCpf(JTCPF.getText());
            cliente.setDataNascimento(JTDataNasc.getText());
            cliente.setEmail(JTEmail.getText());
            cliente.setNome(JTNome.getText());
            cliente.setTelefone(JTTelefone.getText());
            pessoaDAO.update(cliente);
            clienteDAO.update(cliente);
            jLabelNotificacao.setText("OK - Dados do cliente atualizados com sucesso!");
            JTDataNasc.setText("");
            JTEmail.setText("");
            JTNome.setText("");
            JTTelefone.setText("");
            JTCPF.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(JFCadastroSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void JTDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTDataNascActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        ClienteDAOPG clienteDAO = new ClienteDAOPG();
        PessoaDAOPG pessoaDAO = new PessoaDAOPG();
        try {
            Cliente cliente = clienteDAO.retrieveOneByCPF(JTCPF.getText());
            clienteDAO.delete(cliente);
            pessoaDAO.delete(cliente);
            jLabelNotificacao.setText("OK - Cliente deletado com sucesso!");
            jButtonEditar.setVisible(false);
            jButtonExcluir.setVisible(false);
            jButtonCadastrar.setVisible(false);
            JTDataNasc.setText("");
            JTEmail.setText("");
            JTNome.setText("");
            JTTelefone.setText("");
            JTCPF.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(JFCadastroSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTCPF;
    private javax.swing.JTextField JTDataNasc;
    private javax.swing.JTextField JTEmail;
    private javax.swing.JTextField JTNome;
    private javax.swing.JTextField JTTelefone;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNotificacao;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
